apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "dev-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "500m"
        memory: "750Mi"
      min:
        cpu: "10m"
        memory: "5Mi"
    - type: "Container"
      max:                                  # maximum no. CPU and memory container can use inside pod
        cpu: "500m"
        memory: "750Mi"
      min:                                  # minimum no. CPU and memory container can use inside pod
        cpu: "10m"
        memory: "5Mi"
      default:                              # The default maximum no. of CPU and memory an individual container can consume.
        cpu: "100m"
        memory: "100Mi"
    - type: openshift.io/Image              # maximum image size can be pushed
      max:
        storage: 1Gi
    - type: openshift.io/ImageStream        # maximum no. of image tags and versions that an imagestream resourse allow
      max:
        openshift.io/image-tags: 10
        openshift.io/images: 20
    - type: "PersistentVolumeClaim"         # maximum & minimum sizes allowed for a pvc
      max:
        storage: "50Gi"
      min:
        storage: "1Gi"
